apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddit-clone-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reddit-clone-apps
  template:
    metadata:
      labels:
        app: reddit-clone-pipeline
    spec:
      containers:
        - name: reddit-clone-pipeline
          image:vesaki/reddit-clone-pipeline::1.0.0-12
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: "500m"
          ports:
            - containerPort: 3000
